services:
  - type: web
    name: music-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PATH
        value: /opt/render/project/src/.local/bin:/usr/local/bin:/usr/bin:/bin
